### ISSUE TITLE
Game freezes while hero crosses terrain border

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#1008]
When hero runs from one terrain type to another, we can notice a small freeze of gameplay.
![lag](https://user-images.githubusercontent.com/55348946/87150853-8a1c3a00-c2bb-11ea-837e-4efb0861102a.jpg)

**Comment by ihhub** [comment]
This is due to a fact that we switch music type which takes some time. We should make change it in a separate thread which can be realized in C++11.

**Comment by shprotru** [comment]
Hi @ihhub! May be this is possible to do with `SDL` threading APIs like `SDL_CreateThread`?
Hi @Branikolog, could you answer on question here #981 ?

**Comment by ihhub** [comment]
Hi @shprotru , we should avoid using **SDL** for normal purposes to reduce the dependency from this library.

**Comment by ihhub** [comment]
Most likely bwe won't be able to fix it till we add C++11 support.

**Comment by ihhub** [comment]
What I found is that we have `CheckSum()` function call which returns some magical **id**. This value is never used in the game. Removing this part of the code will speed up music switching.

**Comment by ihhub** [comment]
Hi @Branikolog , could you please retest this issue again? I don't guarantee it has been fixed fully but it should have a shorter delay.

**Comment by Branikolog** [comment]
Hello, @ihhub. Unfortunately, game still experiences a short, but noticeable lag. I'm not sure, if your solution made something better...

**Comment by Branikolog** [comment]
This happens only for MIDI music... When we set rather fast hero speed, this lag is very noticeable...

**Comment by LeHerosInconnu** [comment]
If anyone could give me some information, I have a question about music and sounds, just to know how it works. :)
How are musics and sounds managed in fheroes2?
Does the program call the music and sound files whenever it needs them, or are the music and sounds preloaded into memory at the start of the game and used from memory?
