### ISSUE TITLE
Combat screen, sprite animations pass through walls during siege

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#2028]
In the original game, during a siege, sometimes the sprite animations of the creatures are displayed through the castle wall.
In fheroes2, this also happens.
It would be nice to find a solution to fix this problem in fheroes2.

In original game:

![0Test08](https://user-images.githubusercontent.com/43583994/96351010-127b5980-10b9-11eb-9a0a-67618029d9ac.png)

In fheroes2:

![vlcsnap-2020-10-17-18h08m29s356](https://user-images.githubusercontent.com/43583994/96350221-07bec580-10b5-11eb-974c-66fbc725242d.png)

![vlcsnap-2020-10-17-18h09m17s556](https://user-images.githubusercontent.com/43583994/96350223-0c837980-10b5-11eb-9b61-2600869ca891.png)

![vlcsnap-2020-10-17-17h56m01s670](https://user-images.githubusercontent.com/43583994/96351017-1f984880-10b9-11eb-85a5-8f927c3e226a.png)

Attack Hillstone castle with Roxana.

Here is the save file:
[Hero path castle fh2 01.zip](https://github.com/ihhub/fheroes2/files/5395706/Hero.path.castle.fh2.01.zip)

Here is a video that show the bug encountered:
[Sprite animations pass through walls fh2 01.zip](https://github.com/ihhub/fheroes2/files/5396279/Sprite.animations.pass.through.walls.fh2.01.zip)

**Comment by ihhub** [comment]
Hi @Districh-ru , have we fixed this issue in the past?

**Comment by Districh-ru** [comment]
Hi @ihhub, we did not fix it recently, but as I can see it was partially fixed earlier:


https://github.com/ihhub/fheroes2/assets/113276641/9cc98a60-3c32-4c2d-9a6d-c115f13b8041


Unicorns are rendered correctly, but Red Dragon's wings are to big so sometimes they are rendered at the other side of the castle wall.
