### ISSUE TITLE
Corrupted cutscenes

### ISSUE THREAD

**Issue by J013k** [ihhub/fheroes2#2528]
There is something wrong with "cutscenes" after starting campaign...
At first I have a corrupted image:
![https://i.postimg.cc/sxSZY0gd/FMV-1.png](https://i.postimg.cc/sxSZY0gd/FMV-1.png)
After one\two second(s) everything seems to be fine:
![https://i.postimg.cc/j2XRYz8n/FMV-1a.png](https://i.postimg.cc/j2XRYz8n/FMV-1a.png)

Tested on Win 7 x64, x64_SDL1 and x64_SDL2 (0.8.4).

**Comment by ihhub** [comment]
Hi @J013k, the problem is a bit deeper. The video should be 640x480 resolution but it's not.

**Comment by J013k** [comment]
Yes, you are right.
Intro (filling full screen at 640x480 res):
![https://i.postimg.cc/sDh7sqGc/screen2.png](https://i.postimg.cc/sDh7sqGc/screen2.png)

There is also something else:
![https://i.postimg.cc/fyZys2GH/select.png](https://i.postimg.cc/fyZys2GH/select.png)
At this screen to select "path" (good or evil), rectangle for selecting a character stays "corrupted" at the top.

Without FMVs Roland's path is default:
![https://i.postimg.cc/TYLTVpXL/select-roland.png](https://i.postimg.cc/TYLTVpXL/select-roland.png)

With FMVs I can also select Archi's path:
![https://i.postimg.cc/g0vJvr8q/select-archi.png](https://i.postimg.cc/g0vJvr8q/select-archi.png)

**Comment by ihhub** [comment]
Hi @J013k , would you be able to help us to fix the issue with these cutscenes? I can compile a special build for you with a potential fix. If it works then we can incorporate it into our code base.

**Comment by J013k** [comment]
Of course I can.

**Comment by ihhub** [comment]
Hi @J013k ,

Here is the version of SDL2 x64 release. Please put it in the directory of your fheroes2. Just run the same videos to see if there is any improvement.
[fheroes2_video.zip](https://github.com/ihhub/fheroes2/files/5977296/fheroes2_video.zip)

**Comment by J013k** [comment]
I'm getting this error when I want to start new campaign:
![https://i.postimg.cc/4NzKhdL1/error.png](https://i.postimg.cc/4NzKhdL1/error.png)

Intro FMV plays fine though.

**Comment by ihhub** [comment]
Ah, okay. I've fixed. Please try this one:
[fheroes2_video2.zip](https://github.com/ihhub/fheroes2/files/5977380/fheroes2_video2.zip)

**Comment by J013k** [comment]
By the Gods, you are faster than a cheetah.

Unfortunately it still crashes at line 504:
![https://i.postimg.cc/rws7ddgd/error2.png](https://i.postimg.cc/rws7ddgd/error2.png)

**Comment by ihhub** [comment]
One more time:
[fheroes2_video3.zip](https://github.com/ihhub/fheroes2/files/5977520/fheroes2_video3.zip)

**Comment by J013k** [comment]
No more crashes, but I have a strange aspect ratio in FMV after starting new campaign:
![https://i.postimg.cc/xCrbQ61K/streched.png](https://i.postimg.cc/xCrbQ61K/streched.png)

I still have a corrupted FMV:
![https://i.postimg.cc/Nj5yr3y6/stre2.png](https://i.postimg.cc/Nj5yr3y6/stre2.png)

Here is how it looks like when I choose the main charakter:
![https://i.postimg.cc/tCmJyBrY/streched3.png](https://i.postimg.cc/tCmJyBrY/streched3.png)

So the image is shifted to the bottom...
Everything if fine in the intro FMV.

**Comment by ihhub** [comment]
Ah, okay. I'll fix it.

**Comment by ihhub** [comment]
Hi @J013k , could you please try this?

[fheroes2_video4.zip](https://github.com/ihhub/fheroes2/files/5981450/fheroes2_video4.zip)

**Comment by J013k** [comment]
@ihhub thanks for your next test build.

Here is how a video looks like in org:
![https://i.postimg.cc/DywF5kT5/org.png](https://i.postimg.cc/DywF5kT5/org.png)

Here is how with "video4":
![https://i.postimg.cc/xCPDygpW/video4.png](https://i.postimg.cc/xCPDygpW/video4.png)

So the image is stretched.

I still have some graphical glitches in FMV, especially after changing a "scenario":
![https://i.postimg.cc/4xG0wpVG/video4-bug.png](https://i.postimg.cc/4xG0wpVG/video4-bug.png)
After a few seconds everything is fine.

A screen when you can select your path looks like that:
![https://i.postimg.cc/mDrfj7xk/video4-select.png](https://i.postimg.cc/mDrfj7xk/video4-select.png)

There is no graphical glitches, but probably because the image is stretched, as I mentioned before...

**Comment by ihhub** [comment]
Hi @J013k , yes the image is stretched as it should be. This is how it looks like with the normal videos:
![image](https://user-images.githubusercontent.com/19829520/108076824-d0821480-70a6-11eb-8e48-74f62dad791f.png)
![image](https://user-images.githubusercontent.com/19829520/108076837-d4ae3200-70a6-11eb-95f3-8622f2242d13.png)
The original size of your video is **640 by 240**. This format is used to reduce the size of the video in old days. Seems at least we fixed this issue and I'm merging changes for it.

**Comment by ihhub** [comment]
@J013k . I closed this issue. Please compile or downlaod (in an hour) the newest version of fheroes2 and check on your side. I think the only thing is left is different colors on video. If this is the case please create another issue and we'll try to fix it later :)

**Comment by J013k** [comment]
@ihhub once again thanks for your work.

As for the issue...
The main problem is that I still have these graphical corruptions in FMV:
![https://i.postimg.cc/jSTY3P9y/1.png](https://i.postimg.cc/jSTY3P9y/1.png)
![https://i.postimg.cc/9Mr6wpRH/2.png](https://i.postimg.cc/9Mr6wpRH/2.png)
![https://i.postimg.cc/tC0K7F98/3.png](https://i.postimg.cc/tC0K7F98/3.png)

After one maybe two seconds they are all gone displaying the correct colors....

That is why I add "Corrupted cutscenes" to the title of this issue...

You mentioned a problem with an aspect ratio, 640x240 instead of 640x480.
Now I have a full screen in FMV, as you mentioned because that it is the way that they should be displayed...

So for me a problem with aspect ratio was fixed, but not with graphical corruptions...

My English sometimes fails because it is not my native language, so sorry if you do not understand what I was writing.

**Comment by ihhub** [comment]
I reopebed the issue.

**Comment by J013k** [comment]
@ihhub can you upload any test version (Windows x64 SDL1 or SDL2) with a fix for this issue?
I just want to test it (out of curiosity).

Best regards.

**Comment by Branikolog** [comment]
[fheroes2_windows_x64_SDL2 (0).zip](https://github.com/ihhub/fheroes2/files/6296194/fheroes2_windows_x64_SDL2.0.zip)
Try it. :)

**Comment by J013k** [comment]
At first I'm only getting this error:
![https://i.postimg.cc/br2502pQ/error.png](https://i.postimg.cc/br2502pQ/error.png)
Once I exit and re-launch `fheroes2.exe` everything is fine.

Graphical glitches in FMVs are gone:
![https://i.postimg.cc/QN9NY4Mq/2.png](https://i.postimg.cc/QN9NY4Mq/2.png)

Thanks.

Best regards.

**Comment by ihhub** [comment]
Hi @J013k , these aren't errors actually. Please ignore them.

**Comment by J013k** [comment]
Thanks for confirmation.

**Comment by VortexAcherontic** [comment]
You guys have cut scenes? :(

I struggle to get any at all.
May this be caused by me owning the Heroes 2 Gold Edition on GOG or was this feature temporarily removed or is not yet in the release sources yet?

Ran a fresh 0.9.3 build from source on Linux.
