### ISSUE TITLE
A message, that player was defeated, appears only after AI turn is over

### ISSUE THREAD

**Issue by Branikolog** [ihhub/fheroes2#2625]
During an AI turn, when player loses a hero, whose name is in scenario loss condition list,  the game doesn't stop, until AI turn is over.
A message, that the match is lost should appear at the moment hero was defeated or fled from a battle.
Also, hero list doesn't refresh currently, until player's turn starts. We need to show hero vanishing animation, delete his portrait from the hero list and then show the message.

**Comment by Branikolog** [comment]
Save file. 
[Lose Hero.zip](https://github.com/ihhub/fheroes2/files/5835938/Lose.Hero.zip)

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog I suppose that this PR is already was fixed one way or another. I wasn't able to load your save (it was produced by the version of the game that isn't supported anymore), but I tried to start the map "Merry Men", attack group of archers near village by Robin the Knight and retreat at the first turn. I immediately got the message "You have lost the hero Robin. Your quest is over." and immediately exited to the main menu, red player (AI-controlled) wasn't get the turn.

**Comment by Branikolog** [comment]
Hi, @oleg-derevenetz 
The issue is still on.
AI needs to attack special hero and at the moment the hero is defeated we should watch a message.
[AI defeats hero.zip](https://github.com/ihhub/fheroes2/files/6753304/AI.defeats.hero.zip)
Also, we have a certain problems with this special loss condition. While playing a multiplayer the game doesn't stop, after the hero was defeated... I believe in future we have to set special loss condition for each player, as the original editor allows to set only a single hero to be the condition of win\loss of a scenario.

**Comment by oleg-derevenetz** [comment]
Hi @Branikolog

> AI needs to attack special hero and at the moment the hero is defeated we should watch a message.

Yeah, it seems that AI-related code doesn't check win/loss conditions after each hero action, as `HumanTurn()` currently does.

> While playing a multiplayer the game doesn't stop, after the hero was defeated...

Currently in a multiplayer mode special win/loss conditions of a map are not checked at all (I don't know are they taken into account in OG), you should take all opponent's castles and kill all heroes (or wait for 7 days after last opponent's castle was taken), so in multiplayer mode there are always `WINS_ALL` and `LOSS_ALL` conditions are active.

**Comment by Branikolog** [comment]
> Currently in a multiplayer mode special win/loss conditions of a map are not checked at all (I don't know are they taken into account in OG), you should take all opponent's castles and kill all heroes (or wait for 7 days after last opponent's castle was taken), so in multiplayer mode there are always `WINS_ALL` and `LOSS_ALL` conditions are active.

I see.
In the OG if player loses hero - the game is over. Even in multiplayer... But I'm not sure, if it's correct behaviour in this case...

**Comment by ihhub** [comment]
Bumping the priority for this issue and also marking it as a bug.

**Comment by dood-apo** [comment]
Actually we might consider handling the vanquish/game-loss logic on the beginning of the turns exclusively. This would mean that you get to watch AI's turns before getting a game loss info, but then this behavior could be applied to multiplayer also and everything would be consistent. No matter if it was a special hero lost or a week without a castle has passed, the behavior could be the same for single/multi player. See my comment in #7091

**Comment by oleg-derevenetz** [comment]
> Actually we might consider handling the vanquish/game-loss logic on the beginning of the turns exclusively. This would mean that you get to watch AI's turns before getting a game loss info, but then this behavior could be applied to multiplayer also and everything would be consistent.

Again, _turns_ and _days_ are different things, please do not mix them. If you have 3 players, they will perform 3 _turns_ (each of them will perform one _turn_) in just one _day_. At the moment, checking whether the player is winning or losing (due to the map win/loss conditions) is performed right after each hero's action for human players and once a _turn_ for AI players. However, when a player has lost all of his castles, but not the heroes, he is given 7 _days_ until he is considered defeated, his kingdom will be still alive on _day_ 7 even after completion of his _turn_. I don't see any point in changing this logic, the only thing that can be improved here is to speed up the win/loss condition check for AI players (perform it after each hero's action, just like it is done for human-controlled players), but I think if this is a "bug", it's just a minor one and does not affect the gameplay in any way, except for cosmetic inconvenience.

**Comment by dood-apo** [comment]
Well, I think that even if something is a minor inconvenience it doesn't mean there is no point of addressing it. I think that first and foremost the game-loss logic should be consistent across single and multiplayer modes. How exactly it should look like to be functional for multiplayer and not annoying at the same time for both modes is another matter.

When I was reproducing #7091 on my end (which seems like a bug to me), I've also noticed that the warning that you've lost your castles and you better find one is issued at the end of your first homeless turn, not at the beginning. Even a more minor inconvenience I guess.

**Comment by oleg-derevenetz** [comment]
> which seems like a bug to me - you're told you're done, but you can be challenged to a fight by the next player in line

Warning message clearly says that you have 7 "days", not "turns". It seems to you that this is a bug, but I believe that this is just the right behavior in accordance with what was promised. Nothing more than a difference of opinion.

> I've also noticed that the warning that you've lost your castles and you better find one is issued at the end of your first homeless turn, not at the beginning. Even a more minor inconvenience I guess.

This behavior was replicated from the original game:

https://github.com/ihhub/fheroes2/assets/32623900/4150ed7e-b552-4f52-8fdb-aca0a2661183

**Comment by dood-apo** [comment]
> Warning message clearly says that you have 7 "days", not "turns". It seems to you that this is a bug, but I believe that this is just the right behavior in accordance with what was promised. Nothing more than a difference of opinion.

You definitely have a point there. However, wouldn't you agree that it is a bit weird to lose and still play a battle on the next player's turn?

> I've also noticed that the warning that you've lost your castles and you better find one is issued at the end of your first homeless turn, not at the beginning. Even a more minor inconvenience I guess.
>> This behavior was replicated from the original game

Yeah, I thought it was the same in OG.

> And maybe even worse: "I lost my special hero, but I managed to re-hire it in my castle, so let's just pretend that nothing happened".

Ok, this right here convinced me that postponing game-loss stuff is a bad idea!

**Comment by oleg-derevenetz** [comment]
> You definitely have a point there. However, wouldn't you agree that it is a bit weird to lose and still play a battle on the next player's turn?

Heh, well, the mechanics of the turn-based game are generally somewhat strange in this regard: a strong hero approaches you with the intention of stuffing your face, but you can't immediately run away :) In "real life", you would run away from him, especially if you have a bigger reserve of movement points than him, but... not in the turn-based game. So no, I don't feel anything particularly strange about it... considering all the circumstances.
