### ISSUE TITLE
Adventure map, instant combat with summoned Elementals and Necromancy

### ISSUE THREAD

**Issue by LeHerosInconnu** [ihhub/fheroes2#3786]
Something goes wrong in this case, the Hero gets 1 more Skeleton.
May be linked to this closed issue: https://github.com/ihhub/fheroes2/issues/1496.

Before the combat, Sandro has an army of 32 Skeletons and 31 Vampire Lords.
![vlcsnap-2021-07-02-19h51m30s722](https://user-images.githubusercontent.com/43583994/124314298-74f68600-db72-11eb-9f50-7e18d7b27561.png)

After the instant battle, Sandro's starting army is completely decimated.
(Sandro summoned Elementals during the combat.)
![vlcsnap-2021-07-02-19h23m59s927](https://user-images.githubusercontent.com/43583994/124311303-d10adb80-db6d-11eb-82ea-f63493f01f32.png)

Thanks to the Necromancy skill, Sandro gets 18 Skeletons back at the end of the combat (which also allows him not to disappear from the adventure map because the summoned Elementals will also disappear at the end of the combat).
![vlcsnap-2021-07-02-19h50m31s830](https://user-images.githubusercontent.com/43583994/124314344-89d31980-db72-11eb-916d-9388f67836ba.png)

However, when the human player gets the hand back, on the adventure map, Sandro's army has 19 Skeletons, which is 1 Skeleton in excess.
![vlcsnap-2021-07-02-19h24m20s430](https://user-images.githubusercontent.com/43583994/124311335-dc5e0700-db6d-11eb-8401-a90d2d36afb4.png)

https://user-images.githubusercontent.com/43583994/124311377-eda71380-db6d-11eb-8241-8249b55b7eae.mp4

End the turn.

Here is the save file from related issue: https://github.com/ihhub/fheroes2/issues/3499.
[Before ai embark 02.zip](https://github.com/ihhub/fheroes2/files/6529080/Before.ai.embark.02.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu This one extra skeleton appeared as follows: currently, if hero wins the battle, but it have no troops (only summoned ones), then, after the battle, one unit from the weakest stack is restored. I don't know how OG behaves in this case however.

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu This one extra skeleton appeared as follows: currently, if hero wins the battle, but it have no troops (only summoned ones), then, after the battle, one unit from the weakest stack is restored. I don't know how OG behaves in this case however.

In the original game, if at the end of a combat a hero has none of his starting troops left, he disappears from the adventure map, even if he has summoned Elementals and has some left at the end of the combat.
This is true even if the hero has the Necromancy skill.
The Necromancy skill is only taken into account if the hero still has creatures from his starting army.
So, even with Necromancy, if the hero wins a combat but doesn't have at least one creature left from his starting army, he disappears from the adventure map.

Here is the test scenario file:
[0 9957.zip](https://github.com/ihhub/fheroes2/files/6758489/0.9957.zip)

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu I played with your map, and there is an interesting issue in OG. Yes, if I just spam Elementals, both heroes are considered as losers. However, if I use Resurrect (not Resurrect True) along with Elementals, then I get a winner without an army (literally):

![winner](https://user-images.githubusercontent.com/32623900/124401066-dfa0f080-dd2f-11eb-91b1-9e61602fdfe8.jpg)

I suppose that current logic (when one unit from the weakest stack is restored) was aimed to somehow solve this dubious situation, but in a manner close to the original game (hero is alive, but with a minimal army). What should be happening instead in this situation in fheroes2? Should both heroes be considered as losers in both situations (both with and without Resurrect)?

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu I played with your map, and there is an interesting issue in OG. Yes, if I just spam Elementals, both heroes are considered as losers. However, if I use Resurrect (not Resurrect True) along with Elementals, then I get a winner without an army (literally):
> I suppose that current logic (when one unit from the weakest stack is restored) was aimed to somehow solve this dubious situation, but in a manner close to the original game (hero is alive, but with a minimal army). What should be happening instead in this situation in fheroes2? Should both heroes be considered as losers in both situations (both with and without Resurrect)?

Which version did you test with?
I tried to reproduce your case with the Resurrect and Resurrect True spells with the English Gold version and the English GoG version and in all cases the hero disappears from the adventure map.

If a hero has no more creatures from his starting army in any case he should disappear from the adventure map.
With the Resurrect spell (not Resurrect True), if there is at least one creature left from his starting army (the Resurrect spell has been used on the troop of this creature) then only the hero will have one creature restored for this troop.
If several troops were resurrected with the Resurrection spell (e.g. a troop of Peasants and a troop of Steel Golems), only the most powerful creature is restored (one Steel Golem).

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

> Hi @LeHerosInconnu
> 
> > Which version did you test with?
> 
> I observed this on HoMM2 Gold. Attack hero with elves by hero with peasants (in multiplayer mode), skip turn by elves, spam elementals, then kill peasants by elves, then cast Resurrect on peasants, then kill elves, and get a hero without an army as a result :)

Yes, I managed to reproduce the case explained.
This is clearly a bug in the original game because a hero is not supposed to have no troops in his army.

> Anyway, it looks like there is no reason to replicate this dubious mechanics in fheroes2.

Yes, this should be fixed. :)

**Comment by LeHerosInconnu** [comment]
Hello @oleg-derevenetz,

I noticed your PR (https://github.com/ihhub/fheroes2/pull/3809) in relation to this problem.
Beware, if at least one creature from the starting army is still present at the end of the combat, even if the troop has been decimated and then resurrected (partially or entirely and all creatures in the troop are considered "temporary") with the Resurrect spell (not Resurrect True), then one creature should be conserved at the end of the combat.
In my test with the English Gold version, it is the strongest creature that is conserved at the end of the combat (one Steel Golem with a troop of Peasants and a troop of Steel Golems), contrary to this closed issue: https://github.com/ihhub/fheroes2/issues/775.

**Comment by oleg-derevenetz** [comment]
Hi @LeHerosInconnu currently one creature from the weakest stack is resurrected regardless of using Resurrection - just because the hero still have some army (doesn't matter - resurrected or summoned) at the end of the battle. It's not right. It looks like issue with Resurrection is a separate one (currently there is no logic at all in the code for a such behavior), and I propose to move it to the separate issue.
