### ISSUE TITLE
Air & Water Summoning Altar passability

### ISSUE THREAD

**Issue by lleonis** [ihhub/fheroes2#4234]
### Preliminary checks

- [X] I've checked that there aren't [**other open issues**](https://github.com/ihhub/fheroes2/issues?q=is%3Aissue) on the same topic.
- [X] I've checked that this issue is reproducible on the [**latest snapshot build**](https://ihhub.github.io/fheroes2/INSTALL.html#snapshots-latest-builds).

### Platform

Linux

### Describe the bug

Air Summoning Altar and Water Summoning Altar doesn't let the hero pass from the side. At least the right side has wrong passability. Savefiles attached from fheroes2 0.9.7 and original HoMM2.

### Save file

[altar.zip](https://github.com/ihhub/fheroes2/files/7198279/altar.zip)

### Additional info

Both savefiles are multiplayer hot seat. There is an air altar in the northwest and a water altar in the northeast, each one has a hero nearby.
Fheroes2 savefile: blue player 3rd hero for air, green player 2nd hero for water.
HoMM2 savefile: blue player for air, green player for water.

**Comment by ihhub** [comment]
Hi @lleonis , could you please try the latest snapshot build? I think your issue should be fixed. You have to start a new game for the same map to verify it as passability is set at the start of the map's game.

**Comment by lleonis** [comment]
@ihhub thanks for your quick reply. I have tried the latest snapshot build. Air Altar is OK, but Water Altar is still not passable from the entrance to the right.
Had a brief look at commit 82f71cf, I have a guess where the problem might be. In contrast to Air Altar, the Water Altar doesn't seem to have a top and a bottom tile on the right side, just one at the bottom. This might cause undesired result in `isTallObject()` and `updatePassability()`. Only a wild guess though, but maybe helps.

**Comment by ihhub** [comment]
Hi @lleonis , actually it has:
![image](https://user-images.githubusercontent.com/19829520/135279827-c27330fd-db46-425a-91f3-030f33933d7b.png)

Could you please try this: in `bool isDetachedObjectType( const MP2::MapObjectType objectType )` function add another case `case MP2::OBJ_WATERALTAR:`? I think it should solve the issue. I can't test it as I don't have the map.

**Comment by ihhub** [comment]
Ah, I actually do have it! Let me see...
